version: '3.1'

services: 
  serverless:
    build: ./serverless
    command: bash -c "sh -c /tmp/entrypoint.sh"    
    restart: always
    tty: true
    #do not mount file ./serverless to docker image
    ports:
      - 3000:3000