service: postsapi
provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action: "*"
      Resource: "*"
plugins:
  - serverless-offline
custom:
  serverless-offline:
    host: 0.0.0.0
functions:
  - ${file(./routes-offline/v2/user.yml)}