service: postsapi-base
provider:
  name: aws
  stage: ${opt:stage}
  runtime: nodejs8.10
  region: ${opt:region}
  memorySize: 1024 # Overwrite the default memory size. Default is 1024
  timeout: 10 # The default is 6 seconds. Note: API Gateway current maximum is 30 seconds
  logRetentionInDays: 14 # Set the default RetentionInDays for a CloudWatch LogGroup
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:*
      Resource: "arn:aws:logs:*:*:*" 
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "arn:aws:dynamodb:${opt:region}:*:*"

functions:
  generalAuthorizerV1:
    handler: generalAuthorizer.handler
    environment:
      SECRET: ${self:custom.config.encryption.secret}
custom:
  # NOTE: Change this if you plan to use/deploy this template!
  config: ${file(config.yml)}
resources:
  Resources:

    # Rest API
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: postsapi
        Description: Posts API Gateway
        
    # Rest API Paths
    ApiGatewayResourceRootV1:
      Type: AWS::ApiGateway::Resource
      Properties:
        RestApiId: { Ref: "ApiGatewayRestApi" }
        ParentId: { Fn::GetAtt: "ApiGatewayRestApi.RootResourceId" }
        PathPart: v1
    ApiGatewayResourceRootV2:
      Type: AWS::ApiGateway::Resource
      Properties:
        RestApiId: { Ref: "ApiGatewayRestApi" }
        ParentId: { Fn::GetAtt: "ApiGatewayRestApi.RootResourceId" }
        PathPart: v2

  Outputs:
    # RestApi resource ID (e.g. ei829oe)
    RestApiId:
      Value:
        Ref: ApiGatewayRestApi
      Export:
        Name: postsapi-base-${opt:stage}-RestApiId
    # RestApi Root Resource (the implicit '/' path)
    RootResourceId:
      Value:
        Fn::GetAtt: ApiGatewayRestApi.RootResourceId
      Export:
        Name: postsapi-base-${opt:stage}-RootResourceId
    # The IAM Role for Lambda execution
    IamRoleLambdaExecution:
      Value:
        Fn::GetAtt: IamRoleLambdaExecution.Arn
      Export:
        Name: postsapi-IamRoleLambdaExecution
    # Root Path Resources
    ApiGatewayResourceRootV1:
      Value:
        Ref: ApiGatewayResourceRootV1
      Export:
        Name: postsapi-base-${opt:stage}-ApiGatewayResourceRootV1
    ApiGatewayResourceRootV2:
      Value:
        Ref: ApiGatewayResourceRootV2
      Export:
        Name: postsapi-base-${opt:stage}-ApiGatewayResourceRootV2